# Generated by Django 3.2.4 on 2021-06-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenFisico',
            fields=[
                ('id_examenfisicoPK', models.AutoField(primary_key=True, serialize=False)),
                ('tension_arterial', models.CharField(blank=True, max_length=30, null=True, verbose_name='TA')),
                ('frecuencia_cardiaca', models.CharField(blank=True, max_length=30, null=True, verbose_name='FC')),
                ('frecuencia_respiratoria', models.CharField(blank=True, max_length=30, null=True, verbose_name='FR')),
                ('temp_ax', models.CharField(blank=True, max_length=30, null=True, verbose_name='TEMP AX')),
                ('sindrome_at', models.CharField(blank=True, max_length=30, null=True, verbose_name='SAT')),
                ('fio', models.CharField(blank=True, max_length=30, null=True, verbose_name='FIO-2')),
                ('pam', models.CharField(blank=True, max_length=30, null=True, verbose_name='PAM')),
                ('avm', models.CharField(blank=True, max_length=30, null=True, verbose_name='AVM')),
                ('modo', models.CharField(blank=True, max_length=30, null=True, verbose_name='MODO')),
                ('noradrenalina', models.CharField(blank=True, max_length=30, null=True, verbose_name='Noradrenalina')),
                ('atracurio', models.CharField(blank=True, max_length=30, null=True, verbose_name='Atracurio')),
                ('vc', models.CharField(blank=True, max_length=30, null=True, verbose_name='VC')),
                ('peep', models.CharField(blank=True, max_length=30, null=True, verbose_name='PEEP')),
                ('prono_dias', models.CharField(blank=True, max_length=30, null=True, verbose_name='Prono Días')),
                ('pao_fio', models.CharField(blank=True, max_length=30, null=True, verbose_name='PAO2/FIO2')),
                ('pi', models.CharField(blank=True, max_length=30, null=True, verbose_name='PI')),
                ('peso', models.CharField(blank=True, max_length=50, null=True, verbose_name='Peso')),
                ('piel_mucosa', models.TextField(blank=True, null=True, verbose_name='Piel y Mucosas')),
                ('neurologico', models.TextField(blank=True, null=True, verbose_name='Neurologico')),
                ('cardiopulmonar', models.TextField(blank=True, null=True, verbose_name='Cardiopulmonar')),
                ('abdomen', models.TextField(blank=True, null=True, verbose_name='Abdomen')),
                ('genitourinario', models.TextField(blank=True, null=True, verbose_name='Genitourinario')),
                ('musculoesqueletico', models.TextField(blank=True, null=True, verbose_name='Musculoesqueletico')),
            ],
            options={
                'verbose_name': 'ExamenFisico',
                'verbose_name_plural': 'ExamenFisicos',
                'db_table': 'tb_examenfisico',
            },
        ),
    ]
