# Generated by Django 3.2.4 on 2021-06-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenfisico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenfisico',
            name='abdomen',
            field=models.TextField(blank=True, default='-', null=True, verbose_name='Abdomen'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='atracurio',
            field=models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='Atracurio'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='avm',
            field=models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='AVM'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='cardiopulmonar',
            field=models.TextField(blank=True, default='-', null=True, verbose_name='Cardiopulmonar'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='fio',
            field=models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='FIO-2'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='frecuencia_cardiaca',
            field=models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='FC'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='frecuencia_respiratoria',
            field=models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='FR'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='genitourinario',
            field=models.TextField(blank=True, default='-', null=True, verbose_name='Genitourinario'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='modo',
            field=models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='MODO'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='musculoesqueletico',
            field=models.TextField(blank=True, default='-', null=True, verbose_name='Musculoesqueletico'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='neurologico',
            field=models.TextField(blank=True, default='-', null=True, verbose_name='Neurologico'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='noradrenalina',
            field=models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='Noradrenalina'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='pam',
            field=models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='PAM'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='pao_fio',
            field=models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='PAO2/FIO2'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='peep',
            field=models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='PEEP'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='peso',
            field=models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='pi',
            field=models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='PI'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='piel_mucosa',
            field=models.TextField(blank=True, default='-', null=True, verbose_name='Piel y Mucosas'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='prono_dias',
            field=models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='Prono Días'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='sindrome_at',
            field=models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='SAT'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='temp_ax',
            field=models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='TEMP AX'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='tension_arterial',
            field=models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='TA'),
        ),
        migrations.AlterField(
            model_name='examenfisico',
            name='vc',
            field=models.CharField(blank=True, default='-', max_length=30, null=True, verbose_name='VC'),
        ),
    ]
