# Generated by Django 3.2.4 on 2021-06-29 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenfisico', '0002_auto_20210628_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenfisico',
            name='abdomen',
        ),
        migrations.RemoveField(
            model_name='examenfisico',
            name='cardiopulmonar',
        ),
        migrations.RemoveField(
            model_name='examenfisico',
            name='genitourinario',
        ),
        migrations.RemoveField(
            model_name='examenfisico',
            name='musculoesqueletico',
        ),
        migrations.RemoveField(
            model_name='examenfisico',
            name='neurologico',
        ),
        migrations.RemoveField(
            model_name='examenfisico',
            name='piel_mucosa',
        ),
    ]
