# Generated by Django 3.2.4 on 2021-06-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudLaboratorio',
            fields=[
                ('id_solicitudlabPK', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'SolicitudLab',
                'verbose_name_plural': 'SolicitudLabs',
                'db_table': 'tb_solicitudlab',
            },
        ),
    ]
