# Generated by Django 3.2.4 on 2021-06-26 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicamento', '0001_initial'),
        ('examenfisico', '0001_initial'),
        ('resultadolaboratorio', '0001_initial'),
        ('historiaclinica', '0001_initial'),
        ('cultivo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id_evolucionPK', models.AutoField(primary_key=True, serialize=False)),
                ('nro_cama', models.IntegerField(blank=True, null=True, verbose_name='Nro. de Cama')),
                ('fecha_hora', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('dias_domo', models.IntegerField(blank=True, null=True, verbose_name='Dias en Domo')),
                ('analisis', models.TextField(blank=True, null=True, verbose_name='Análisis')),
                ('plan', models.TextField(blank=True, null=True, verbose_name='Plan')),
                ('estado', models.CharField(blank=True, default='Activo', max_length=20, null=True)),
                ('id_examenfisicoFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='examenfisico.examenfisico')),
                ('id_historiaclinicaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historiaclinica.historiaclinica')),
                ('id_medicoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_resultadolabFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultadolaboratorio.resultadolab')),
            ],
            options={
                'verbose_name': 'Evolucion',
                'verbose_name_plural': 'Evoluciones',
                'db_table': 'tb_evolucion',
            },
        ),
        migrations.CreateModel(
            name='det_tratmiento_evolucion',
            fields=[
                ('id_det_tratamiento_evolucionPK', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('indicacion', models.CharField(default='-', max_length=500, verbose_name='Indicacion')),
                ('id_evolucionFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evolucion.evolucion')),
                ('id_medicamentoFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicamento.medicamento')),
            ],
            options={
                'db_table': 'det_tratamiento_evolucion',
            },
        ),
        migrations.CreateModel(
            name='det_cultivo_evolucion',
            fields=[
                ('id_det_cultivo_evolucionPK', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('estado', models.CharField(blank=True, max_length=50, verbose_name='Estado')),
                ('id_cultivoFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cultivo.cultivo')),
                ('id_evolucionFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evolucion.evolucion')),
            ],
            options={
                'db_table': 'det_cultivo_evolucion',
            },
        ),
    ]
