# Generated by Django 3.2.4 on 2021-06-26 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id_historiaPK', models.AutoField(primary_key=True, serialize=False)),
                ('cod_historiaclinica', models.IntegerField(verbose_name='HC')),
                ('fecha_ingresohospital', models.DateTimeField(verbose_name='Fecha de ingreso a Hospital')),
                ('fecha_ingresodomo', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de ingreso a Domo')),
                ('grado_instruccion', models.CharField(max_length=100, verbose_name='Grado Instrucción')),
                ('proviene', models.CharField(max_length=100, verbose_name='Proviene de')),
                ('antecedente', models.CharField(max_length=700, verbose_name='Antecedentes')),
                ('historia_enfermedad_actual', models.TextField(verbose_name='Historia de la Enfermedad Actual')),
                ('impresion_diagnostica', models.TextField(verbose_name='Impresion Diagnostica')),
                ('id_medicoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_pacienteFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
            options={
                'verbose_name': 'HistoriaClinica',
                'verbose_name_plural': 'HistoriaClinicas',
                'db_table': 'tb_historiaclinica',
            },
        ),
    ]
