# Generated by Django 3.2.4 on 2021-06-29 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudlaboratorio', '0001_initial'),
        ('medidasgenerales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicacion',
            fields=[
                ('id_indicacionPK', models.AutoField(primary_key=True, serialize=False)),
                ('dieta', models.TextField(blank=True, null=True, verbose_name='Dieta')),
                ('terapia_respiratoria', models.TextField(blank=True, null=True, verbose_name='Terapia Respiratoria')),
            ],
            options={
                'verbose_name': 'Indicacion',
                'verbose_name_plural': 'Indicaciones',
                'db_table': 'tb_indicacion',
            },
        ),
        migrations.CreateModel(
            name='det_solicitud_indicacion',
            fields=[
                ('id_det_solicitud_indicacionPK', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField(auto_now=True, verbose_name='Fecha Solicitud')),
                ('id_indicacionFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicacion.indicacion')),
                ('id_solicitud_laboratioFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudlaboratorio.solicitudlaboratorio')),
            ],
            options={
                'db_table': 'det_solicitud_indicacion',
            },
        ),
        migrations.CreateModel(
            name='det_indicacion_medida_general',
            fields=[
                ('id_det_indicacion_medidaPK', models.AutoField(primary_key=True, serialize=False)),
                ('id_indicacionFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicacion.indicacion')),
                ('id_medida_generalFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medidasgenerales.medidasgenerales')),
            ],
            options={
                'db_table': 'det_indicacion_medida_general',
            },
        ),
    ]
