# Generated by Django 3.2.4 on 2021-06-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoLab',
            fields=[
                ('id_resultadolabPK', models.AutoField(primary_key=True, serialize=False)),
                ('lab_gb', models.CharField(blank=True, max_length=20, null=True, verbose_name='GB')),
                ('lab_hb', models.CharField(blank=True, max_length=20, null=True, verbose_name='HB')),
                ('lab_ph', models.CharField(blank=True, max_length=20, null=True, verbose_name='PH')),
                ('lab_got', models.CharField(blank=True, max_length=20, null=True, verbose_name='GOT')),
                ('lab_neu', models.CharField(blank=True, max_length=20, null=True, verbose_name='NEU')),
                ('lab_htco', models.CharField(blank=True, max_length=20, null=True, verbose_name='HTCO')),
                ('lab_pco', models.CharField(blank=True, max_length=20, null=True, verbose_name='PCO2')),
                ('lab_gpt', models.CharField(blank=True, max_length=20, null=True, verbose_name='GPT')),
                ('lab_lin', models.CharField(blank=True, max_length=20, null=True, verbose_name='LIN')),
                ('lab_cr', models.CharField(blank=True, max_length=20, null=True, verbose_name='CR')),
                ('lab_hco', models.CharField(blank=True, max_length=20, null=True, verbose_name='HCO3')),
                ('lab_pt', models.CharField(blank=True, max_length=20, null=True, verbose_name='PT')),
                ('lab_cay', models.CharField(blank=True, max_length=20, null=True, verbose_name='CAY')),
                ('lab_urea', models.CharField(blank=True, max_length=20, null=True, verbose_name='UREA')),
                ('lab_alb', models.CharField(blank=True, max_length=20, null=True, verbose_name='ALB')),
                ('lab_po', models.CharField(blank=True, max_length=20, null=True, verbose_name='PO2')),
                ('lab_plq', models.CharField(blank=True, max_length=20, null=True, verbose_name='PLQ')),
                ('lab_na', models.CharField(blank=True, max_length=20, null=True, verbose_name='NA')),
                ('lab_eb', models.CharField(blank=True, max_length=20, null=True, verbose_name='EB')),
                ('lab_cl', models.CharField(blank=True, max_length=20, null=True, verbose_name='CL')),
                ('lab_k', models.CharField(blank=True, max_length=20, null=True, verbose_name='K')),
                ('lab_lact', models.CharField(blank=True, max_length=20, null=True, verbose_name='LACT')),
                ('lab_dd', models.CharField(blank=True, max_length=20, null=True, verbose_name='DD')),
            ],
            options={
                'verbose_name': 'Resultadolab',
                'verbose_name_plural': 'Resultadolabs',
                'db_table': 'tb_resultadolab',
            },
        ),
    ]
