# Generated by Django 3.2.4 on 2021-06-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultadolaboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadolab',
            name='lab_alb',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='ALB'),
        ),
        migrations.AlterField(
            model_name='resultadolab',
            name='lab_cay',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='CAY'),
        ),
        migrations.AlterField(
            model_name='resultadolab',
            name='lab_cl',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='CL'),
        ),
        migrations.AlterField(
            model_name='resultadolab',
            name='lab_cr',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='CR'),
        ),
        migrations.AlterField(
            model_name='resultadolab',
            name='lab_dd',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='DD'),
        ),
        migrations.AlterField(
            model_name='resultadolab',
            name='lab_eb',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='EB'),
        ),
        migrations.AlterField(
            model_name='resultadolab',
            name='lab_gb',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='GB'),
        ),
        migrations.AlterField(
            model_name='resultadolab',
            name='lab_got',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='GOT'),
        ),
        migrations.AlterField(
            model_name='resultadolab',
            name='lab_gpt',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='GPT'),
        ),
        migrations.AlterField(
            model_name='resultadolab',
            name='lab_hb',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='HB'),
        ),
        migrations.AlterField(
            model_name='resultadolab',
            name='lab_hco',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='HCO3'),
        ),
        migrations.AlterField(
            model_name='resultadolab',
            name='lab_htco',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='HTCO'),
        ),
        migrations.AlterField(
            model_name='resultadolab',
            name='lab_k',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='K'),
        ),
        migrations.AlterField(
            model_name='resultadolab',
            name='lab_lact',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='LACT'),
        ),
        migrations.AlterField(
            model_name='resultadolab',
            name='lab_lin',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='LIN'),
        ),
        migrations.AlterField(
            model_name='resultadolab',
            name='lab_na',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='NA'),
        ),
        migrations.AlterField(
            model_name='resultadolab',
            name='lab_neu',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='NEU'),
        ),
        migrations.AlterField(
            model_name='resultadolab',
            name='lab_pco',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='PCO2'),
        ),
        migrations.AlterField(
            model_name='resultadolab',
            name='lab_ph',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='PH'),
        ),
        migrations.AlterField(
            model_name='resultadolab',
            name='lab_plq',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='PLQ'),
        ),
        migrations.AlterField(
            model_name='resultadolab',
            name='lab_po',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='PO2'),
        ),
        migrations.AlterField(
            model_name='resultadolab',
            name='lab_pt',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='PT'),
        ),
        migrations.AlterField(
            model_name='resultadolab',
            name='lab_urea',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='UREA'),
        ),
    ]
