# Generated by Django 3.2.4 on 2021-06-29 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solucion',
            fields=[
                ('id_solucionPK', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Solucion')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Solucion',
                'verbose_name_plural': 'Soluciones',
                'db_table': 'tb_solucion',
            },
        ),
        migrations.CreateModel(
            name='det_solucion',
            fields=[
                ('id_det_solucionPK', models.AutoField(primary_key=True, serialize=False)),
                ('detalle_indicacion', models.TextField(blank=True, max_length=200, null=True, verbose_name='Indicacion')),
                ('id_indicacionFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicacion.indicacion')),
                ('id_solucionFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solucion.solucion')),
            ],
            options={
                'db_table': 'det_solucion_nombresolucion',
            },
        ),
    ]
