# Generated by Django 3.2.4 on 2021-06-29 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TratamientoIndicacion',
            fields=[
                ('id_tratamientoindicacionPK', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Tratamiento')),
                ('descripcion', models.TextField(verbose_name='Descripcion Indicacion')),
            ],
            options={
                'verbose_name': 'TratamientoIndicacion',
                'verbose_name_plural': 'TratamientoIndicaciones',
                'db_table': 'tb_tratamiento_indicacion',
            },
        ),
        migrations.CreateModel(
            name='det_tratamiento_indicacion',
            fields=[
                ('id_det_tratamiento_indicacionPK', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('id_medicamentoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamento.medicamento')),
                ('id_tratamiento_indicacionFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tratamientoindicacion.tratamientoindicacion')),
            ],
            options={
                'db_table': 'det_tratamiento_indicacion',
            },
        ),
    ]
